trigger:
  - master

jobs:
  - job: 'test_linux'
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        Python27:
          python.version: '2.7'
        Python34:
          python.version: '3.4'
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 5

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: python -m pip install --upgrade pip
      - script: pip install pytest-azurepipelines
      - script: pip install -e .[test]

      - script: pytest tests/ --test-run-title="Linux Test with junitxml"
        displayName: 'pytest with junitxml flag'

  - job: 'test_windows'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Python27:
          python.version: '2.7'
        Python34:
          python.version: '3.4'
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 5

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: python -m pip install --upgrade pip
      - script: pip install pytest-azurepipelines
      - script: pip install -e .[test]

      - script: pytest tests/ --test-run-title="Linux Windows with junitxml"
        displayName: 'pytest with junitxml flag'
